AllCops:
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'public/**/*'
    - 'config/initializers/devise.rb'
  RunRailsCops: true
  DisplayCopNames: true
  StyleGuideCopsOnly: false

Documentation:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'lib/**/version.rb'

Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  Enabled: false
